language: go
go: 1.15.x
services:
- docker
sudo: required 
env:
  global:
    - secure: n+5+1KQ80lRMlOi4zSEaYk39BRAvpoyZRhO38Xbommo/v8xNwG1vkF7+XyHzqtUGBNj20PFuwfX65MID7ol615D5+/t8c//8LUtfx1fSa+gOWMvelVWLWuYeSxYJDdobm+dw2p1eUr4MDps5/FWpBObiLPu+aIQ3iNgt3fA7+8ATGN/NVGw2n8jKd98Xz70q9Wfs3IiE7WBCgAoz8CAzl4Q/tu7zxJhgGb1oeNB6gCzbDodl/lI6NCFE5kX5ZxWaueoRcMLp5X2MzCFDRGYO5+Mzrq6nCC46nGpbkPtnQ2U1GjooEU99Qqov+a4vsKrx+6bFXzSDFaXDBnoevIJRZHdJkDJx6A/pNraVe/miaVTWxjLWHTSqbO2A2sWo/H4gUNShiOF3RxUWxdp6vAKlXWtVJbMBcX5rdD/E0G4cUDaKq7awe3U6NVflVzA10Y4paJ202DMXr+ln5a/NgkEQ9JrN1hK4fAU69i6x+droJNFu/d0ZxUPQ1dMQFT2oah1N7Flx0ULbMTVDWy4XLzaAJdsA2lfNh7qPfBJ1pXIKGcWJL4rGewB6z6HcgpQ+B1luXfaGiaxyFfhQJptxtNjOBnWVyzI1zCShEtRIkT7Ltaa8Fl5ul7zNZUhUMOZXh9GrFLI1YgwN9X27t1JvZZBlXfQUWJnDPLj5b2FNYIuDUZw=
    - secure: JYIHbZLt1MOWkQQN2jbBn/NMEGjXcBwLEAb4f/7FD+RNhsKDRksLRutK27tviPiOAB/PvrIemKViRQxxP4+rNq5fhldpE39cFtP4c7S6A+Y7LyBukj867oontBPlzLR3p0Ra5dni15qSAuof7l+NOjbahl4M91/uZwDArjcKehskpUW8It0x32Hh4NLIf9hlJlTQy3MFcpxydkg4HCNsX+5WtDydtehutZvzyu8h1Y+5mabxTc7VcF5P7SoSqqkSayMI9rNYfMffEAnz8r4BXtRy0zA1+vY+tapb6cIEO41wLqetdQaLXrn/jegUdHRFFr3zaAepPw+HiokABXX1HeF5XyrEjU0WyJU7gUxC5d16WCD48ShyEe7Rz9khk+wuZ64NoYXzOsJINAbS9i1zouqNLR7+f1K71G09PJBniY0WKJvUnzTIlNvN/SaOuqeBr6vuloo+TrdZEH2ryggsfck0ljR4D6CjOgbpgHR/AFD0Z2WoS1HE8R7uxDMzvrL5F24DzGLO3oGysPehBofhlJBAsN6ymWs4I8hg1KMVF4qX2Epp/NcFAgnoe4g5L8mJixFUtF7HK576qfJluMHT54y8HP8SwlP3f8+15kw6oRMTIqEmZsHO3X/nvzcPKVUEOXX/lRvL73UfkWnpKkJ5caDjFd0GDM9Asc4j+NHcTmQ=
    - secure: lhFJq34XQoqUNdqsQ8ne7ddalofoajEb8Vaa50VtfzVUZAEtLto2nYW4DKPumW/AyoaYJI0rdBu5Buw8WbMcTVVW1fE212fqBDZW1jzQKUM95QcS61FZ3uSkOD1ZMQGfr7CS2O6jPOxx58T4yrI3tYIPLR/u3vb3dvM9cvlbiieEXAfMW06+DvrQqAI/tjJjY9rGkd2K5GlDtMV1M8ciM4Fo5+yhDTdWABgJVDaDZXLek1KZnnIW0t/0qMKRQ9ktPrDJKepiyU9gZdinThsz1RL0A7asVgP7NTNoOjIrzTPQGgLy5v7K+f59sY92xxQW/9Nv6Fa9PD9L+mR5WyqS9jWr/BWnLDBKCcwnmafyEXwwUvAM/k6kHI7Jg9/afcN4GmJTHj5pPmnyrvU776HwAWb2MDB5iCCNiKYofQFeHZBhEaLjB3y6ZVi5Kyrj/aNnt9hs9/ZQMdLm8HwstgkaOuSrZnWRMe5vWEZUUDOw485pQT8YyztgBKFEz+iIKDuK/J/Bunpr7cQvdmIR2M9MrM+Sa0gy451vQnAfLUmT6P9EVwVQf8hmGpgQJVwza/LsufdJt66vjnp8YPtT9gZfoYl6QuBndVlkhSnN8wXpVObgiUEz88cfM8C2LMmGkYUWXbGln6WoPo8reuHWArN3DDmmY6wF8sh6EHYs9hGj2fY=
    - secure: PPX/fv3wke1nRoPrBpjnMKq8XNlrlvSTgHy0y6gpxH4utaX//qYkz9SY0U6OmeKFFcBykGP24X7d2HYMLjMqGcZmFw0rsE1FWt5onXhRrOkjYrH4V5ntCB7Lu4tCKmldPMW6ntu00ukJkHreWd/NirbfEH46+7MKbKy82fHA4Vvq5ib1bCvKGWvVOK819e9kzaL30y6YK2hhsiRMUiNcAVWXHyKdJDiabusrt9WaoF0Tmijh6JJZWowFuqkc6TgTKZyxLHbGkgDD07L30ijhTDlPdNHRK4s+dlDVrtMxgpOVPKWDeuYsy8jyPQ5xGh4oCQl5JaqreflOmC1aEbe6zHsuA2EzPBjIl/BBGkBQyyYj+eyRr0K14Ujz759vf5boe/opzc9t6sdqyH0IQTCK6E1dtHtT+7ujEtGf640IFGLffph4Hs/YfFTxkjpBTa3c/rPnn6NTfA2FJQhCCNiPULQd0Lil6B/FMgu+et+39dPe6SnidBFIDdlNZUx6g+Ke5wLzIl8YXsJTbnP5jEA+6m3WPY4DH2+aF2C7z2C3cPNKj5s8j8KFJJPUIUKDSxPQQ6qsyTfknVHoY0+aEst9ywqKGtsUjP+103rZWNvOYcbTKdHp97bilLljn/V1kIb6xt39cKX+IyPKBBHv1sbKbRire2QCa2RxBmpH4B1dGm8=
    - secure: Bk1clZS9f5aXCTo53pVuz2+fy+0DDiPh1qT8w6x+HnRtUvwjYXkA4oLtr9mHmOz/HIxRsBoCLqyLvAfBB8xQ7Of+4+Dapr1lbqYMdCu63ECJIlKfUm7Tob+u2XbMPfckcsF8zNxGhGy2QtkcrNappgk8JCs4yv8asulPGMGwoSiyfc+r8MkU7H6IMYgGOtbjRYDZYVAp/AXgNlPSXua7ZbKP3rq9Po1h5WFnetqhvBQcHikvb6SJ6FpjPM/an6/e4WRX5bwPyNhfjiiiEOi1VP+pQR0E9U/lSgviDtdCPjsZWYcOhZAYrjF4VCOFTSPgQ6aam6YlkvrbSU2H+OEt8Xzxp/4M4FpRnmi9REY69K9WMcXHEKnVxhioGOnxuTbokEvNhZiK4ep5VkEnuSza79YjpaawhjXT5Hl7/ykyHt+ikFOu3Cwh8J+B/vMvw+tDpMn18oZfGzapnAehqOXwp5cPjM5SE0xWpHRV71uHs9Jl4ytbpkpuN5cDQjXk+PBcbkgsWFwuqXnwL+tKj0nGVV4lFTpVslox3BHhcggUVCSSDhMalkP26VMiw5+BnSFj6WeWjqFj5yUa5rC6Iy4nd749v2VPwZjn2CzO2/uCDS0kY74xdsR5IUoi2MFFR8AG9bS8Y+Ju6ySCRHQA3hxj50HELnjoJy5Bub0lBvWBEaE=
install:
- git submodule update --init
- go mod download
before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...
script:
- make test-ci
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: i1yCqHh8mIarJJx0hpxvR2DJkUTcHZyM+t1qETZq0Mep/CG2rFaw673PR7ZzJsO8SSVUaXBIZzNeTYdn1C+4+9AD9Isw7Ey7jrkPJLSgJciKuGtUIHWqbi+tO15l8RrJiDyRwHdAvhjW3DAw2F9mfu76UDLC+fRdz5oy/EPHObyUm4Zz9+2FACd61pWszzuxvFQTdL9vUZDlVHW60sYifWQoEBKlQNyO131M7TEbUI9y6Pyldw2e1JSYYvZ+VK2yxnTKph/wOz2omvfdqAq4vgyqtUPv3/G/ry6tUz2PrRj2Q410LHezV/zCV8cUoAGWgrjkCKwhekf1AovoGJhyMgqx+ZXSpVHrB3+ZTaUo8+X1UIjOw4Xc2ZCwah1pPEjn3rDEbNX+torCOByu8AGPV4R/CGu3E9nCGBCyrWOyQPfgteFIEo60hYs186cQxHAmUBlQQ5fudmCBuF3NF5YJ5viLrWsXFWt3WLoQ+Unmri7G34F0+K0ueCCQ+jbPGe1xuZmdtzKaQKGwi5bdy47n+khVt4Iu4sI/DW1iOXQKPa+jhwqGbuZNnSgl/tdL9kluxB5m/h4/etsD3l9bfPsyz8AJWOnynWakAry8TrG1CbwBdIEgROfFr2QrtJNx2RcW9byKt1qhpUJCJmYI3aDNxMm2HQrKroOd/G4cKXtuORg=
  file_glob: true
  file: release/*
  on:
    tags: true
    repo: bonedaddy/circuit-breaker
cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
notifications:
  email: false